### ISSUE TITLE
Newline in lf-spawn-new is messing up the spawn

### ISSUE THREAD

**Issue by EmmChriss** [TeddyDD/kakoune-lf#13]
Pretty self-descriptive;
The command should be on one line, because, the terminal command starts the user configured default shell, which, among others can be fish, which doesn't follow the POSIX protocol, and thus fails to interpret the escaped newline.
Just so you know, the `%{ ... }` is basically just a form of string in kakoune, and doesn't escape anything (except for }, when { is not found somewhere earlier)

**Comment by TeddyDD** [comment]
It's weird, I'v got Fish (3.0.2) as my default shell and I have no issues with this.

**Comment by EmmChriss** [comment]
That really is weird, I have it too, and I just assumed that was the problem, since after removing the newline it works fine.
I shall further investigate this issue
